# Generated by Django 5.0.3 on 2024-03-16 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20170525_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('quantity', models.IntegerField(default=10)),
                ('cat_price', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default=None, max_length=15)),
                ('customer_surname', models.CharField(default=None, max_length=15)),
                ('trackID', models.CharField(max_length=12)),
                ('source_address', models.CharField(max_length=300)),
                ('destination_address', models.CharField(max_length=300)),
                ('sending_date', models.DateField()),
                ('arrival_date', models.DateField(null=True)),
                ('isReceived', models.BooleanField(default=False)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.category')),
                ('corporateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.corporateuser')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackID', models.CharField(max_length=12)),
                ('source_address', models.CharField(max_length=300)),
                ('destination_address', models.CharField(max_length=300)),
                ('sending_date', models.DateField()),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('isReceived', models.BooleanField(default=False)),
                ('price', models.FloatField(default=7.0)),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_app.category')),
                ('userID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
